apiVersion: batch/v1
kind: Job
metadata:
  generateName: free
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: mp12
        image: jasonyoungsim/mp12:latest
        command: ["python", "classify.py"]
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "0.9"
          env:
          - name: APP_ENV
            value: development
          - name: DATASET
            value: mnist
          - name: TYPE
            value: ff
      restartPolicy: Never