apiVersion: batch/v1
kind: Job
metadata:
  generateName: free
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: lastmp
        image: jasonyoungsim/lastmp:latest
        command: ["python", "classify.py"]
        resources:
          limits:
            cpu: "900m"   
          requests:
            cpu: "900m"
        env:
          - name: APP_ENV
            value: "development"
          - name: DATASET
            value: "mnist"
          - name: TYPE
            value: "ff"
      restartPolicy: Never