apiVersion: batch/v1
kind: Job
metadata:
  name: free
spec:
  hard:
    requests.cpu: "900m"
  template:
    spec:
      containers:
      - name: free
        image: jasonyoungsim/mp12:latest
        command: ["python", "classify.py"]
        env:
          - name: APP_ENV
            value: development
          - name: DATASET
            value: mnist
          - name: TYPE
            value: ff
      restartPolicy: Never
  backoffLimit: 4