apiVersion: batch/v1
kind: Job
metadata:
  name: premium
spec:
  template:
    spec:
      containers:
      - name: premium
        image: jasonyoungsim/mp12:latest
        command: ["python", "classify.py"]
        resources:
          requests.cpu: "900m"
        env:
          - name: APP_ENV
            value: development
          - name: DATASET
            value: kmnist
          - name: TYPE
            value: cnn
      restartPolicy: Never
  backoffLimit: 4