apiVersion: batch/v1
kind: Job
metadata:
  generateName: premium
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: mp12
        image: jasonyoungsim/mp12:latest
        command: ["python", "classify.py"]
        resources:
          limits:
            cpu: "1"   
          requests:
            cpu: "900m"
        env:
          - name: APP_ENV
            value: development
          - name: DATASET
            value: kminst
          - name: TYPE
            value: cnn
      restartPolicy: Never            